### ISSUE TITLE
issue using local storage to store backup info

### ISSUE THREAD

**Issue by pmario** [buggyj/savetiddlers#3]
Did some tests on ubuntu 17.04 ... It seems the plugin is using local storage to save info about backups. 

This mechanism isn't working, if the user changes the backup folder setting after the first backup is made. ... I did run into a lot of problems really quickly. 

The second problem is, that local storage is maxed to 5MB in chrome. So as soon as someone will reach the limit (probably in years) it will cause very hard to find problems!

**So my proposal is**, to use a different backup strategy, known form "tape backup rotation strategies". So we don't need to remember, what we have already stored. We just have to rotate the backup "set name" eg: A, B, C, ..., G, H, A, B, ... and **remember** that **1 character** per TW file-name. 

I'd like to propose a slightly modified [tower of hanoi](https://en.wikipedia.org/wiki/Backup_rotation_scheme) rotation scheme.  Which uses 8 "tapes". So the "oldest" backup will be 128 saves away. The number of files is fixed to 9 ... 8 backups and 1 active file.

**Comment by buggyj** [comment]
The storage  is one entry per tiddlywiki, so you have probably 5000 names of tiddlywikis paths before the storage is exhausted. (assuming 256 charater pathname). We could remove the entries as well - for the first backup of the day could delete the entire storage (save once per day, not once per 24hr).

**Comment by pmario** [comment]
the point here is, that I think 1 backup per day isn't good enough. .. I personally want a much more fine grained behaviour. 

With TWclassic we had a plugin, that created backups per minute, per hour, per day of week, per day of month, per year(permanenty stored) ... That was a bit too much, but you get the idea?

This behaviour was possible, because we could read the filesystem and did know, what's there. ... Now we need a mechanism, that is very flexible, but has no real file access.

**Comment by buggyj** [comment]
I don't think this is difficult, if you only save once per period, then you only need to keep track for what has been saved that period. - I'll have a go....

**Comment by buggyj** [comment]
I think that once a hour or once a day.

**Comment by buggyj** [comment]
overwriting a backup is not very useful, (i.e. it overwrites with the same version we are storing) so it would be better either create unique hourly backups (which is a lot of files) or find the prevously saved tw in the download directory and redownload it as the backup.

**Comment by pmario** [comment]
> overwriting a backup is not very useful

If you don't want to create an unlimited number of files, you have to! I know, that HD space is cheap, but imo that's not true for SSDs. So I personally don't want unlimited backup files, because of SSDs in my system ;)

>i.e. it overwrites with the same version we are storing

Yes. That's the purpose of redundancy. ... You have 2 of the same thing at the same time. So if you mess up one, you are able to reset to the second "clone"

So eg: if auto-save is switched off and you change your TW, but you are _not_ happy with the result, it's easy to switch back to the last version. .... 

--------

Let me explain the structure I have in mind.

The "tower of hanoi" rotation schema, that I did suggest, is taken from "tape" based backup strategies. They did have a slightly different goal: "Don't use too many tapes". IMO we can have up to 10 or 11 files, __plus__ may be, a monthly backup, which will not be overwritten.

I'm using only 4 backups here, because of table size. We may user 10 or 11 files with our mechanism

 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |9 |10|11|12|13|14|15|16
-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-
A| |A| |A| |A| |A| |A| |A| |A| 
||B||||B||||B||||B||
||||C||||||||C|||
||||||||D||||||||D

You are right. There will be always 2 files, that have the same content. 

- The "live" version of the file, which will be edited and
- one backup: A, B, C or D

As you can see. This system needs 8 saves until the backup D is used the first time. ... I personally don't want this behaviour.

I want to populate the backups like this: A, B, C, D and then switch to the above system. A, B, A, C, A, B, A, D ...

As you can see. The backup D is populated with the 4th save, but then it needs an other 8 saves until it is overwritten again. ... And IMO that's the nice thing here, if we use 10 or 11 files. 

With eg: 11 files we will populate them with the first 11 saves. So the first backups will all have a very early version of our TW. ... BUT the 11th backup will be overwritten the next time after 1024 saves. ... 

So I think that's a really good mechanism, with a very predictable HD usage pattern and good recovery possibilities. I personally use the built in file compression mechanism of the OS. So HD space isn't a real problem anymore. 

## Conclusion: 

Since all names are 100% predictable, we only need to store 1 states in the local storage.

 - One save counter per TW  ... So we can calculate the next backup char.

There may be some more config elements, for the user:

 - Number of files, that should be used
 - backup directory name
 - Init Save counter (dangerous!)

--------

IMO there's also the possibility, that we create eg: tagged saves. Whith a special save button. So the user can decide to save "milestone" backups, that are out of order. 

... just some thoughs. ... The truth is. ... I will implement this behaviour anyway, because I personally want to have it that way.

**Comment by buggyj** [comment]
I understand what you are saying, but  it does not suit how I use tiddlywiki, - I typically have 5 wikis open and clip content into them (via tiddlyclip), I need auto save and there maybe multiple saves a minute. 

I will add a license so you can clone the repo.

**Comment by pmario** [comment]
>I need auto save and there maybe multiple saves a minute.

IMO that's no problem. A day has 1440 minutes. That would mean 1 save per minute for 24h. Or let's say you work 8h and save 3 times per minute (every 20 seconds), that's exactly 1440. 

So just set number of files to 11 and you can't even overwrite the last backup K (11) within one day. 

You are right. The granularity isn't 1, but imo there is enough redundancy, to recover from a problem, with 11 files + 1 active version. ... There won't ever be more than 12 files per TW, to review. 

just my thoughts.

**Comment by buggyj** [comment]
I would like to get something tested before ff57 release so I will probably just have a 24h backup at first, then add more options later.

**Comment by pmario** [comment]
np

**Comment by buggyj** [comment]
@pmario I think we can have different backup options, allowing the user to choose which scheme(s) they want - I have opened a new issue for this #14

**Comment by pmario** [comment]
I do have a working prototype, with works slightly different than your approach. ... I hope to upload something to github .... later today. ... late :)

I want to have the different functions in different directories, which requires the use of require and webpack. 

I'm also using a slightly modified version of path.js module from nodejs, to mess with paths. ... I actually wanted to use the default shim from webpack, but it seems, it only handles *nix systems. ... I'll have to have a closer look here. May be upstream needs a new target: web-extensions :)

I also want to have ContentScript as minimal as possible. IMO no path handling at all. ... background should do the work. 

As I wrote in the OP, I only want to store the minimum state info in the local storage. Because of the limited browser API to manage files. ...
