### ISSUE TITLE
request: change the download folder only for tw

### ISSUE THREAD

**Issue by tulakalbeyo** [buggyj/savetiddlers#35]
i would like to leave my traditional download folder intact, but be able to modify the specific folder where i save my tiddlywiki... is that possible? thanks!

**Comment by buggyj** [comment]
As a security feature, firefox (and chrome) only allow automatic downloads to the 'download' folder or a subdirectory within it.  For this reason the plugin only allows you to specify the name of the subdirectory (within the download folder) for tiddlywikis.

**Comment by tulakalbeyo** [comment]
i see.. oh well..  thanks for replying ^_^
