### ISSUE TITLE
FF 58.0.2: savetiddlers complains about 2nd savetiddlers already installed

### ISSUE THREAD

**Issue by blutsvente** [buggyj/savetiddlers#38]
I am recently getting this error: savetiddlers has detected that another tiddlysaver called savetiddlers is install. Currently only one saver is supported therefore - savetiddlers will not activate

This is on Windows 7 (64-bit).

**Comment by blutsvente** [comment]
A full re-install of Firefox didn't help. I tried to use a different add-on instead (TiddlyWiki File Save by Mario Pietsch) which throws the same error, complaining about savetiddlers already running. Not surprising, it seems you guys have copy&pasted the same code where you create a widget with the name "tiddlyfox-message-box".
Unfortunately I can't fix it myself because of the rigid measures Firefox has implemented to fend off rogue add-ons (signature, checksums).

**Comment by buggyj** [comment]
@blutsvente hmm... could you try and download an empty tiddlywiki from https://tiddlywiki.com/empty.html and see if you can save it.

**Comment by buggyj** [comment]
@blutsvente  savetiddlers and TiddlyWiki File Save both implement the same check on tiddlyfox-message-box to ensure that only one extension is enabled at the same time (otherwise both would try to save the same tiddlywiki at the same time.) When you installed "TiddlyWiki File Save" did you disable "savetiddlers"?

**Comment by buggyj** [comment]
@blutsvente what version of "savetiddlers" are you using?

**Comment by blutsvente** [comment]
@buggyj 
1. I removed savetiddlers before "I tried TiddlyWiki File Save". 
2. I am using the latest version of savetiddlers.
3. With the empty tiddlywiki it seems to work -> I can try to start from a fresh TW5 template (we use our own customized version) and import my tiddlers into it.
Update: this helped; somehow the tiddlywiki was corrupted!?
