### ISSUE TITLE
Automatic saving not possible

### ISSUE THREAD

**Issue by kanyi** [buggyj/savetiddlers#39]
The directory change function is cool. :-)
I created a shiny new directory with your plug-in. It's create it. And save there my file. Then I try to save it agan, the program gave me these error message:

> 
> Automatic saving not possible.
> As your TW is not within the contolled directory a manual save is required

Why can't re-write the saved file? Debian 9, Firefox 59.0.2 (64-bit).

**Comment by uboubo** [comment]
Same here in Vivaldi on Ubuntu 16.04

**Comment by harmlessdrudge** [comment]
I'm seeing this with Firefox 59.0.2 (64bit) on Linux Mint 18.3 (Cinnamon).

I created a directory "wiki" under Downloads and tried to use that. Savetiddlers wants to save to wiki/wiki
