### ISSUE TITLE
"gecko": {

### ISSUE THREAD

**Issue by agamat** [buggyj/savetiddlers#43]
In chrome: I got error: Unrecognized manifest key 'applications' 

    "applications": {
        "gecko": {
            "id": "random201709301147@buggyjef.uk",
            "strict_min_version": "56.0"
        }
    },

**Comment by cook** [comment]
I had meet the same problem.

**Comment by buggyj** [comment]
This key value of for firefox. -It does not stop the extension from working on my chrome setup in xubuntu....
