### ISSUE TITLE
Seems to be broken on Firefox 68.0

### ISSUE THREAD

**Issue by ghost** [buggyj/savetiddlers#44]
Since upgrading to Firefox 68.0, I get the following message when loading the file:

`savetiddlers has detected that another tiddlysaver called savetiddlers is install. Currently only one saver is supported therefore - savetiddlers will not activate`

If I load the HTML in a text editor and remove...

`<div id="tiddlyfox-message-box" style="display: none;" data-message-box-creator="savetiddlers"></div>`

...from the file, I can load it and save **once**. However, refreshing breaks it again. Downgrading to an earlier Firefox version fixes it.

Can this check be disabled or fixed? I'd prefer not to lock my Firefox version due to security concerns.

**Comment by buggyj** [comment]
This is a problem with how tiddlywiki classic creates a new version (saves itself), it should not include the message box. I will see if I can work around this issue....

**Comment by buggyj** [comment]
![image](https://user-images.githubusercontent.com/2855795/61157647-09cfc700-a4f7-11e9-9158-829ecb7d73bc.png)


So now it is not possible to read files, tw classic will manifest this bug.

**Comment by ghost** [comment]
Understood. Thank you for finding the reason!

**Comment by buggyj** [comment]
setting **security.fileuri.strict_origin_policy** option in **about:config** to **false** gets things working again -- for now!

**Comment by ghost** [comment]
Excellent, thank you!

**Comment by buggyj** [comment]
@kralik There is a new version - but it only has been tested by me - make a backup before you try it!
https://github.com/buggyj/savetiddlers/releases/tag/0.9

**Comment by pmario** [comment]
@buggyj see:  [assets/classic/inject.js](https://github.com/pmario/file-backups/commit/1b63a9fc0f8a0950f0ef0b6320a4e0e18c9e335a#diff-34ac94a23300b40f94f776ac82682bceR49) ... These changes fixed the problem for me. ...

There is a difference in path handling for windows and unix systems. .. It seems older versions did ignore an additional "/" character on unix systems in the `file:///` + `/home/...` (my old code)

my new code only has `file://` ... and a check in line 51 ...

Just a hint, since I don't know your code good enough.

**Comment by buggyj** [comment]
@pmario thanks I will take a look.

**Comment by skierpage** [comment]
> @kralik There is a new version - but it only has been tested by me - make a backup before you try it!
> https://github.com/buggyj/savetiddlers/releases/tag/0.9

I tried it. I'm using mGSD 3.1.9 beta (an adaptation of TiddlyWiki with impressive features) with Firefox Nightly 71.0a1 Build ID 20190911095413 on Fedora Linux.

- ✔ I didn't get warning about a second save tiddlers at startup (issue #38)

If I edit a Tiddler and click "done"
- ✔ it displays its usual yellow box showing
     Main TiddlyWiki file saved
     Backup saved
- ✔ Firefox's download arrow turns blue, reports a completed download, and there is a more recent timestamp on my mGSD.html file.
- ✗ The new file doesn't include my edits.
- ✗ There is no new backup in `tiddlywikilocations/twbackup`

If I click "save changes"
- ✔ I get the same yellow box and download
- ✔ The new mGSD.html file does have my changes! Hooray, ship it!
- ✗ There is no new backup in `tiddlywikilocations/twbackup`

My success with saving this old TiddlyWiki file has been sporadic, but it has worked at times in 2019. It has a lot of old personal data in it.

**Comment by skierpage** [comment]
I think I'm trying the newest 0.1 version, and it's still not saving a backup. My TiddlyWiki hasn't saved backups for a while so I don't think it's related to this issue. I'll create a new one with the fix.
