### ISSUE TITLE
weird behavior in Vivaldi

### ISSUE THREAD

**Issue by YakovL** [buggyj/savetiddlers#49]
Hi, I've tested SaveTiddlers in Vivaldi (2.8, with TWC 2.9.2, after testing in Chrome) and found that the plugin doesn't work as expected. Since Vivaldi is Chromium-based I think this is something to note at least (the problem may exist in Opera and others too).

The behavior is the following:
* if I put TW into the tiddlywikilocations subfolder and try to save it, it gets saved into the downloads folder itself
* if I put TW into the download folder, it gets saved but into another file (tw 2.9.2.html is saved into tw 2.9.2 (1).html)

Best regards,
Yakov.

**Comment by buggyj** [comment]
HI YakovL, Thanks for the feedback. SaveTiddlers was working with Opera but has never worked with Vivaldi. Unfortunately life is too short for me to try and fix all issues!

**Comment by YakovL** [comment]
Hi BuggyJ, I understand, just hoped that you can point how to figure whether it's a Vivaldi bug or smth else. Thanks anyway for the plugin!

**Comment by buggyj** [comment]
the download router plugin also has trouble with vivaldi, so I think there is a problem with the browser rather than SaveTiddlers:
https://forum.vivaldi.net/topic/26372/how-to-make-download-router-chrome-ext-work-on-vivaldi-or-make-some-kind-function-similair
