### ISSUE TITLE
Only working in FF69 if I save preferences and reload.

### ISSUE THREAD

**Issue by Coburn** [buggyj/savetiddlers#50]
I'm using PVHL's [Woas](https://github.com/PVHL/woas) project and File Backups does not save the file unless I open Preferences, save the preferences, and reload the page. Even then it doesn't always work. Having the same behavior with [File Backups](https://github.com/pmario/file-backups).

**Comment by buggyj** [comment]
savetiddlers is designed to work with tiddlywikis, so I dont think using it will Woas will work.

**Comment by Coburn** [comment]
For some reason it slipped my mind to file the issue on Woas. I'll try that.
