### ISSUE TITLE
Unrecognized manifest key 'applications'

### ISSUE THREAD

**Issue by Pumpapa** [buggyj/savetiddlers#52]
Chrome Version 92.0.4515.131 (Official Build) (64-bit) (linux)
![Screenshot_2021-08-10_22-42-09](https://user-images.githubusercontent.com/1771485/128932257-06ccdd0d-cfe1-48d1-b7e7-e71337536412.png)

**Comment by buggyj** [comment]
Thanks for the report. It is anoying that chrome does not just ignore the firefox key, however it does not break so I will leave this as 'will not fix'

**Comment by Pumpapa** [comment]
Oh my goodness, yes. Now you mention this I noticed that the extension icon was flushed off the right on my window, so I didn't see it, but it is indeed there. Thanks for all the good work, Buggyj!
