### ISSUE TITLE
Manifest Version 2 Deprecated

### ISSUE THREAD

**Issue by MedicoreV8** [buggyj/savetiddlers#53]
It seems that google has deprecated Manifest version 2. I have no idea what or how this all works so I can't change the plugin. Meaning there is no way of automatically saving tiddlers in chrome anymore (under v 0.11).

**Comment by buggyj** [comment]
google have said that the v2 deprecation is paused:

https://groups.google.com/u/0/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E

under what operating system and with what browser and browser version are you using the extension?
